FROM python:3.13.2-slim-bullseye

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libjpeg-dev \
    libcairo2 \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Virtual environment
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN mkdir -p /code
WORKDIR /code

COPY requirements.txt /tmp/requirements.txt
COPY ./src /code
RUN pip install --upgrade pip && pip install -r /tmp/requirements.txt

COPY ./boot/docker-run.sh /opt/run.sh
RUN chmod +x /opt/run.sh

# No CMD here; it is handled via compose.yaml
